using System;

namespace TPCASTWindows.Utils
{
	public enum ConnectCode
	{
		SSID_NOT_MODIFIED,
		SSID_MODIFIED,
		INIT_CHECK_ROURTER_FAIL,
		BEGIN_CHECK_ROUTER,
		CHECK_ROUTER_FAIL,
		CHECK_ROUTER_SUCCESS,
		CHECK_ROUTER_SSID_NOT_MODIFIED,
		CHECK_ROUTER_SSID_MODIFIED,
		BEGIN_CHECK_HOST,
		CHECK_HOST_FAIL,
		CHECK_HOST_SUCCESS,
		CHECK_CABLE_FAIL,
		CHECK_CABLE_SUCCESS,
		CHECK_VR_SUCCESS,
		SHOW_GUIDE_IMAGE,
		NONE
	}
}
